// app/layout.tsx
import { SessionProvider } from "next-auth/react";  // SessionProviderをインポート
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

// フォントの設定
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// メタデータの設定
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// レイアウトのコンポーネント
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          {/* Headerをここで表示 */}
          <Header />

          {/* ページのコンテンツ */}
          <main>{children}</main>

          {/* Footerをここで表示 */}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
